FROM node:22-alpine

WORKDIR /app

RUN corepack enable && corepack prepare pnpm@10.8.1 --activate

COPY service/package.json ./service/
RUN pnpm --dir ./service install --no-frozen-lockfile

COPY service ./service

WORKDIR /app/service

RUN pnpm prisma generate
RUN pnpm build

ENV NODE_ENV=production
ENV PORT=4000

EXPOSE 4000

CMD ["pnpm", "start:prod"]
